services:
  api-clientes:
    container_name: springboot-apiclientes
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - rede_bdclientes
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bd_clientes

  postgres:
    image: postgres:16
    container_name: postgres_apiclientes
    environment:
      POSTGRES_DB: bd_clientes
      POSTGRES_USER: user_bdclientes
      POSTGRES_PASSWORD: pass_bdclientes
    ports:
      - "5434:5432"
    networks:
      - rede_bdclientes
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq_apiclientes
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - rede_bdclientes

networks:
  rede_bdclientes:
    external: true

volumes:
  postgres_data:
